---
- name: Helm add kubernetes charts repo elastic
  community.kubernetes.helm_repository:
    name: elastic
    repo_url: https://{{ global.registry }}/chartrepo/vanillastack-logging

- name: Install elasticsearch
  community.kubernetes.helm:
    name: elasticsearch
    chart_ref: elastic/elasticsearch
    release_namespace: kube-logging
    values: "{{ lookup('template', 'elastic_values.yml.j2') | from_yaml }}"
