---
#- name: Install fluentd
#  community.kubernetes.helm:
#    name: fluentd
#    chart_ref: stable/fluentd
#    release_namespace: kube-logging
#    values: "{{ lookup('template', 'fluentd_values.yml.j2') | from_yaml }}"
#    create_namespace: true
#    wait: true
- name: Install filebeat
  community.kubernetes.helm:
    name: filebeat
    chart_ref: elastic/filebeat
    release_namespace: kube-logging
    values: "{{ lookup('template', 'filebeat_values.yml.j2') | from_yaml }}"
    create_namespace: true
    wait: true

