---
- name: Add elastic repository
    community.kubernetes.helm_repository:
    name: elastic
    repo_url: https://helm.elastic.co

- name: Create kube-logging namespace
  k8s:
    wait: yes
    name: kube-logging
    kind: Namespace
    state: present
