---
# defaults file for deploy-kubernetes

kubernetes:
  init_opts: ""
  kubeadm_opts: ""
  service_cidr: "10.96.0.0/12"
  loadBalancer:
    virtualIP: 135.181.48.19
    clusterDomain: ""
  clusterName: kube
  resetCluster: false
  version: "1.19"
  crioVersion: "1.18"
  kubeadmin_config: /etc/kubernetes/admin.conf

## the following may be historic keys that are no longer needed

#pod_network_cidr: "10.244.0.0/16"
#kube_version: "1.17"
#cidr: "10.244.0.0/16"
#clustername: kube
