---
openstack:
  namespace: openstack
  chartRepo: "https://{{global.registry}}/chartrepo/vanillastack-openstack"
  publicDomain: "alderaan.cop.cloudical.net"
  publicProto: "http"
  region: RegionOne
  # releases available:
  # - train
  # - ussuri (not tested)
  release: "stein"
  mariadb:
    enabled: true
    chartName: mariadb
    chartVersion: 0.1.0
    createService: false
    replicas: 3
    persistence:
      enabled: true
      storageClass: "rook-ceph-block"
      diskSize: 30Gi
  rabbitmq:
    enabled: true
    chartName: rabbitmq
    chartVersion: 0.1.0
    createService: false
    replicas: 2
    persistence:
      enabled: true
      storageClass: "rook-ceph-block"
      diskSize: 20Gi
  memcached:
    enabled: true
    chartName: memcached
    chartVersion: 0.1.0
    createService: false
    replicas: 1
  ceph:
    enabled: true
    rook:
      cephMonitors: ['rook-ceph-mon-a.rook-ceph.svc.cluster.local:6789', 'rook-ceph-mon-b.rook-ceph.svc.cluster.local:6789', 'rook-ceph-mon-c.rook-ceph.svc.cluster.local:6789']
      namespace: "rook-ceph"
      fsid: "602a7124-e4ba-43fd-a6f7-00bd574329d8"
  cinder:
    enabled: true
    chartName: cinder
    chartVersion: 20200728
    createService: true
    rbd:
      enabled: true
      rbdPool: cinder.volumes
      rbdUser: cinder
      rbdBackupUser: cinder-backup
      rbdBackupPool: cinder.backups
    api:
      replicas: 2
      v1Enabled: false
    volume:
      replicas: 1
      osapiVolumeWorkers: 1
    scheduler:
      replicas: 1
    backup:
      enabled: false
      replicas: 1
    endpoints:
      publicURLPrefix: "cinder"
  glance:
    enabled: true
    chartName: glance
    chartVersion: 20200728
    createService: true
    defaultBackend: rbd
    rbd:
      enabled: true
      cephAppName: glance
      rbdPool: glance.images
      rbdUser: glance
    api:
      replicas: 2
      v1Enabled: false
      version: 2
    registry:
      replicas: 2
      v2Enabled: true
    endpoints:
      publicURLPrefix: "glance"
  heat:
    enabled: true
    chartName: heat
    chartVersion: 20200728
    createService: true
    api:
      replicas: 2
    cfn:
      replicas: 2
    cloudwatch:
      replicas: 2
    engine:
      replicas: 2
    endpoints:
      publicURLPrefix: "heat"
      cfPublicURLPrefix: "heat-cfn"
  horizon:
    enabled: true
    chartName: horizon
    chartVersion: 20200728
    createService: true
  keystone:
    enabled: true
    chartName: keystone
    chartVersion: 20200728
    createService: true
    endpoints:
      publicURLPrefix: "keystone"
    api:
      replicas: 2
    admin:
      username: admin
      password: password
  libvirt:
    enabled: true
    chartName: libvirt
    chartVersion: 0.1.0
    createService: false
  neutron:
    enabled: true
    chartName: neutron
    chartVersion: 20200728
    createService: true
    tunnelInterface: "ens192"
    server:
      replicas: 2
    l3:
      ha: false
      maxAgentsPerRouter: 1
      haNetworkType: vxlan
      dhcpAgents: 2
    endpoints:
      publicURLPrefix: "neutron"
  nova:
    enabled: true
    chartName: nova
    chartVersion: 20200728
    createService: true
    apiMetadata:
      replicas: 1
    placement:
      replicas: 2
    osapi:
      replicas: 2
    conductor:
      replicas: 2
    consoleauth:
      replicas: 2
    scheduler:
      replicas: 1
    novncproxy:
      replicas: 1
    endpoints:
      publicURLPrefix: "nova"
      novncURLPrefix: "novnc"
    libvirt:
      # bare metal = kvm, VMs = qemu
      virtType: kvm
      # bare metal = host-passthrough or host-model, vm= none
      cpuMode: host-model
  openvswitch:
    enabled: true
    chartName: openvswitch
    chartVersion: 0.1.0
    createService: false
