---
- name: "copy nginx-ingress.yaml"
  template: 
    src: nginx-ingress.yaml.j2  
    dest: /tmp/nginx-ingress.yaml

- name: "create Nginx Ingress namespace"
  k8s:
    name: "{{ ingress.namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: "add helm repository - stable"
  shell: "helm repo add stable https://kubernetes-charts.storage.googleapis.com/ "

- name: "update helm repositories"
  shell: "helm repo update"

- name: "helm install nginx-ingress"
  shell: "helm upgrade --install nginx-ingress stable/nginx-ingress --namespace {{ ingress.namespace }} -f /tmp/nginx-ingress.yaml" 
  retry: 3
  delay: 10

- name: "delete nginx-ingress.yaml"
  file:
    path: /tmp/nginx-ingress.yaml
    state: absent
