---
- name: Install neccessary packages
  apt:
    pkg:
    - gnupg
    - git
    - python-pip
    - python3-pip
    - python-kubernetes
    - python3-kubernetes
    update_cache: yes

- name: Add key from keyserver
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{ item }}"
  loop:
    - 93C4A3FD7BB9C367
    - 8BECF1637AD8C79D

- name: Add key for cri-o repos
  apt_key:
    url: "{{ item }}"
  loop: 
    - "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.18:/1.18.3/Debian_Unstable/Release.key"
    - "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_Unstable/Release.key"
    - "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_10/Release.key"
    - "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    - "https://baltocdn.com/helm/signing.asc"
    - "https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key"

- name: Add repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  loop:
    - "deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main"
    - "deb https://apt.kubernetes.io/ kubernetes-xenial main"
    - "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_10/ /"
    - "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.18:/1.18.3/Debian_Unstable/ /"
    - "deb https://baltocdn.com/helm/stable/debian/ all main"
    - "deb https://packages.cloudfoundry.org/debian stable main"

- name: Install packages
  apt:
    pkg: 
      - ansible
      - needrestart
      - helm
      - cf-cli
    update_cache: yes

- name: add hosts entry
  lineinfile:
    regexp: '^(.*){{ loadbalancer_fqdn }}(.*)$'
    path: /etc/hosts
    line: "{{ loadbalancer_virtualip }} api.{{ loadbalancer_fqdn }}"

- name: update hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: '{{ hostvars[item].ansible_host }}.*{{ item }}$'
    line: "{{ hostvars[item].ansible_host }} {{item}}"
    state: present
  with_items: "{{ groups.all }}"

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest

- name: extend var lvm
  lvol:
    vg: "{{ inventory_hostname_short }}-vg"
    lv: var
    size: 100%FREE
    resizefs: true
    shrink: no
