---
- name: generate join token
  block:
  - name: create join token
    command: kubeadm token generate
    register: generated_token

  - name: save token
    lineinfile:
      path: /tmp/cluster_vars.yml
      regexp: '^(.*)token:(.*)$'
      line: "token: {{ generated_token.stdout }}"
      create: true
  delegate_to: '{{ groups.master[0] }}'
#  when: token is not defined or token|length <1

- name: generate certificate key
  block:
  - name: create certificate key
    command: kubeadm alpha certs certificate-key
    register: generated_certificate_key

  - name: save certificate key
    lineinfile:
      path: /tmp/cluster_vars.yml
      regexp: '^(.*)certificate_key(.*)$'
      line: "certificate_key: {{ generated_certificate_key.stdout }}"
      create: true
  delegate_to: '{{ groups.master[0] }}'
# when: certificate_key is not defined or certificate_key|length <1

