---
- name: Install packages
  apt:
    pkg: 
      - kubelet
      - kubeadm
      - kubectl
      - cri-o
      - libgtk2.0-0
    update_cache: yes

- name: configure crio
  lineinfile:
    path: /etc/crio/crio.conf
    regexp: '^(.*)conmon =(.*)$'
    line: 'conmon = "/usr/bin/conmon"'
    backrefs: yes

- name: configure kubelet
  lineinfile:
    path: /etc/default/kubelet 
    regexp: '^(.*)KUBELET_EXTRA_ARGS(.*)$'
    line: 'KUBELET_EXTRA_ARGS=--cgroup-driver=systemd --container-runtime=remote --container-runtime-endpoint="unix:///var/run/crio/crio.sock"'
    create: true

- name: add container repos
  blockinfile:
    path: "{{ item }}"
    block: |
      [registries.search]
      registries = ['docker.io', 'registry.fedoraproject.org', 'registry.access.redhat.com']
    create: true
  with_items:
    - /etc/containers/registries.conf

- name: Make sure a service is running 
  systemd:
    state: started
    enabled: true
    name: crio

- name: load modules
  modprobe: 
    name: "{{ item }}"
    state: present
  with_items:
    - overlay
    - br_netfilter

- name: create bridge traffic config
  sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_file: /etc/sysctl.d/k8s.conf
    reload: yes
  with_items:
    - net.bridge.bridge-nf-call-ip6tables
    - net.bridge.bridge-nf-call-iptables
    - net.ipv4.ip_forward

- name: load Modules
  lineinfile:
    path: /etc/modules
    line: "{{ item }}"      
    create: true
  with_items:
     - br_netfilter
     -  overlay

- name: Disable Swap
  command: swapoff -a

- name: Disable swap permanently, persist reboots
  replace:
    path: /etc/fstab
    regexp: '^(\s*)([^#\n]+\s+)(\w+\s+)swap(\s+.*)$'
    replace: '#\1\2\3swap\4'

- name: Check if kubeadm has already run
  stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: kubeadm_ca

- name: Reset  the cluster if set
  command: kubeadm reset --force
  when: not kubeadm_ca.stat.exists or reset_cluster==true

- name: check if reboot is required
  command: needrestart
  ignore_errors: true
  register: reboot_hint

- name: "Reboot machine to get latest updates"
  reboot:
  when: reboot_hint.rc == 1


