---
- name: Include certificate var
  include_vars:
    file: /tmp/cluster_vars.yml
  when: certificate_key is not defined or certificate_key|length <1

- name: Init Cluster
  command: > 
    kubeadm init --service-cidr {{ service_cidr }} \
                 --pod-network-cidr {{ pod_network_cidr }} \
                 --token {{ token }} \
                 --control-plane-endpoint api.{{ kubernetes.loadBalancer.fqdn }}:6443 
                 --upload-certs \                
                 --apiserver-bind-port 8443 \
                 --certificate-key {{ certificate_key }} \
                 --ignore-preflight-errors=Port-6443 \
                 {{ kubeadm_opts }} \
                 {{ init_opts }}
  register: init_cluster 
