---
- name: Include certificate var
  include_vars:
    file: /tmp/cluster_vars.yml
  when: certificate_key is not defined or certificate_key|length <1

- name: Join to Kubernetes cluster
  command: >
    kubeadm join --token {{ token }} \
                 --discovery-token-unsafe-skip-ca-verification \
                 api.{{ loadbalancer_fqdn }}:6443 

