---
- name: Include certificate var
  include_vars:
    file: main.yml
  when: certificate_key is not defined or certificate_key|length <1

- name: Check if kubeadm has already run
  stat:
    path: "/etc/kubernetes/pki/ca.crt"
  register: kubeadm_ca

- name: join worker if not already
  block:
  - name: reset Master Node
    command: kubeadm reset --force
  
  - name: Join to Kubernetes cluster
    command: >
      kubeadm join --token {{ token }} \
                  --discovery-token-unsafe-skip-ca-verification \
                  {{  loadbalancer_fqdn }}:6443 \
  when: not kubeadm_ca.stat.exists or reset_cluster==true

