---
- name: Check if kubeadm has already run
  become: true
  stat:
    path: "/etc/kubernetes/pki/ca.crt"
  register: kubeadm_crt

- name: Include certificate var
  include_vars:
    file: /tmp/cluster_vars.yml
  when: certificate_key is not defined or certificate_key|length <1

- name: Join to Kubernetes cluster
  command: >
    kubeadm join --token {{ token }} \
                 --discovery-token-unsafe-skip-ca-verification \
                 {{  loadbalancer_fqdn }}:6443 
  when: not kubeadm_crt.stat.exists or reset_cluster==true

