---
- name: Include certificate var
  include_vars:
    file: /tmp/cluster_vars.yml
  when: certificate_key is not defined or certificate_key|length <1

- name: Join to Kubernetes cluster
  command: >
    kubeadm join --token {{ token }} --node-name {{ inventory_hostname_short }} \
                 --discovery-token-unsafe-skip-ca-verification \
                 api.{{ kubernetes.loadBalancer.clusterDomain }}:6443 
