---
- name: create folder
  file: 
    path: "{{ ansible_env.HOME }}/{{ item }}/"
    state: directory
    mode: '750'
    owner: "{{ ansible_env.USER }}"
  loop:
    - "{{ clustername }}"
    - .kube

- name: Copy admin.conf to Home directory
  become: true
  when: init_cluster is succeeded
  copy:
    src: "{{ kubeadmin_config }}"
    dest: ".kube/config"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0640
    remote_src: true

- name: get calico definitions
  get_url:
    url: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ clustername }}/"
  with_items:
    - https://docs.projectcalico.org/manifests/calico.yaml

- name: "Install python dependencies"
  pip:
    name:
      - pyhelm
      - openshift
    extra_args: --ignore-installed

- name: load calico 
  k8s:
    state: present
    src: "{{ ansible_env.HOME }}/{{ clustername }}/calico.yaml"

- name: Wait for control-plane pods become ready
  shell: "kubectl wait --namespace=kube-system --for=condition=Ready pods --all --timeout=600s"
