---
- name: create folder
  file: 
    path: "{{ ansible_env.HOME }}/{{ item }}/"
    state: directory
    mode: '750'
    owner: "{{ ansible_env.USER }}"
  loop:
    - "{{ kubernetes.clusterName }}"
    - .kube

- name: Copy admin.conf to Home directory
  become: true
  when: init_cluster is succeeded
  copy:
    src: "{{ kubeadmin_config }}"
    dest: ".kube/config"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0640
    remote_src: true

- name: install weave
  shell: kubectl apply --wait -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

- name: Wait for control-plane pods become ready
  command: "kubectl wait --namespace=kube-system --for=condition=Ready pods --all --timeout=600s"

- name: restart kubedns
  command: kubectl delete po -n kube-system -l k8s-app=kube-dns
