image: "harbor.cloudical.net/vanillastack/vanilla-ubuntu-base:latest"
services:
  - docker:18.09.7-dind  
variables:
  DOCKER_HOST: tcp://localhost:2375

stages:
  - build_docker_image_dev
  - redeploy
  - run_playbook

build_docker_image_dev:
  only:
    refs:
      - backend
  stage: build_docker_image_dev
  interruptible: true
  script:
    - docker login -u 'robot$build-backend-gitlab.cloudical.net' -p "$HARBOR_ROBOT_KEY_BUILD_BACKEND" harbor.cloudical.net/vanillastack
    - git clone -b backend https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.cloudical.net/vanillastack/vanillastack.git
    - cd vanillastack/backend
    - export DATE=$(date +'%Y%m%d%H%M') && docker build -f docker/dev/Dockerfile -t harbor.cloudical.net/vanillastack/vsinstaller:$DATE .
    - docker push harbor.cloudical.net/vanillastack/vsinstaller:$DATE

redeploy_debian:
  only:
    refs:
      - testing
  stage: redeploy
  interruptible: true
  script:
    - curl $WEBHOOK_REDEPLOY

run_playbook:
  only:
    refs:
      - testing
  stage: run_playbook
  interruptible: true
  script: 
    - mkdir ~/.ssh && echo "$SSH_KEY"|base64 -d>~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
    - git clone -b testing https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.cloudical.net/vanillastack/vanillastack.git
    - cd vanillastack/ansible
    - mv group_vars.testing group_vars
    - ansible-playbook -i inventory.testing type_vanillastack_deploy.yaml

