image: "ubuntu:latest"

stages:
  - redeploy
  - run_playbook
  - build_liveimage

redeploy_debian:
  only:
    refs:
      - testing
  stage: redeploy
  interruptible: true
  script:
    - apt update && apt install -y curl
    - curl $WEBHOOK_REDEPLOY


run_playbook:
  only:
    refs:
      - testing
  stage: run_playbook
  interruptible: true
  script: 
    - apt update && apt install -y git ansible ssh-client
    - ansible-galaxy collection install community.kubernetes
    - mkdir ~/.ssh && echo "$SSH_KEY"|base64 -d>~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
    - git clone -b testing https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.cloudical.net/vanillastack/vanillastack.git
    - cd vanillastack/ansible
    - mv group_vars.testing group_vars
    - ansible-playbook -i inventory.testing type_vanillastack_deploy.yaml


build_liveimage:
  only:
    refs:
      - live-image
  stage: build_liveimage
  script:
    - cd live_image && docker build . -t vanilla_installer
