---
- name: Deploy Rook
  include_tasks: deploy.yaml
  with_items:
    - { name: common, wait: false, delay: 0}
    - { name: operator, wait: true, delay: 10}
    - { name: cluster, wait: true, delay: 10}
    - { name: toolbox, wait: false, delay: 0}
    - { name: storageclass, wait: false, delay: 0}
