---
- name: Deploy Rook
  include_tasks: deploy.yaml
  with_items:
    - { name: common, wait: false, delay: 0}
    - { name: operator, wait: true, delay: 10}
    - { name: cluster, wait: true, delay: 10}
    - { name: toolbox, wait: true, delay: 0}
    - { name: storageclass, wait: false, delay: 0}

- name: Delay for upcoming Rook
  wait_for:
    timeout: 60

- name: wait for CephCluster to come up
  shell: kubectl get cephcluster "{{rook.cluster.name}}" -o json -n "{{rook.namespace}}"|grep HEALTH_OK
  register: kubectl_get_cephcluster
  until: kubectl_get_pods.rc==0
  retries: 120
  delay: 10
