system_domain: testcluster.cloudical.net

kube:
  storage_class: "{{ cloudfoundry.storageclass }}"

features:
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 1024m
    #  cert-manager.io/cluster-issuer: letsencrypt-prod
    #  kubernetes.io/tls-acme: "true"
  eirini:
    enabled: true

