---
commercial_enabled: true # commercial.enabled
make_ha: true # global.isHA
create_extLB: false # global.externalLB
cluster_uuid: "ee582ffa-f6ba-11ea-adc1-0242ac120002" # global.uuid
## global.registry -> repo.registry
staging_tag: "testing" # repo.debian.tag
# possible issuer: "letsencrypt-staging", "letsencrypt-prod" or "certmanager-selfsigned"
LE_issuer_name: "letsencrypt-staging" # tls.issuerName
LE_issuer_mail: "testing@test.vanillastack.cloudical.net" #tls.issuerEmail
loadbalancerIP: 135.181.48.19 # kubernetes.loadBlanacer.virtualIP
clusterTLDomain: test.vanillastack.cloudical.net # kubernetes.loadBlanacer.clusterDomain
reset_environment: false kubernetes.resetCluster
vanillaservices:
  dashboard_enabled: true # kubernetes.dashboard.enabled
  cloudfoundry_enabled: true # cloudfoundry.enabled
  stratos_enabled: true # stratos.enabled
  guacamole_enabled: true # guacamole.enabled
  pgOperator_enabled: true # postgresOperator.enabled
  redis_enabled: true # redis.enabled
  harbor_enabled: true # harbor.enabled
  loggingStack_enabled: true #efkstack.enabled
  monitoring_enabled: true # prometheus.enabled
  kubevirt_enabled: true # kubevirt.enabled
  moodle_enabled: false # moodle.enabled
  keycloak_enabled: true # keycloak.enabled
  openstack_enabled: false # openstack.enabled
# prometheus -> monitoring
