loadbalancer_fqdn: "test.vanillastack.cloudical.net"
loadbalancer_virtualip: 135.181.48.19
# service_cidr: "10.96.0.0/12"
# pod_network_cidr: "10.244.0.0/16"
kube_version: "v1.18.1"

#######################################################################
#######################################################################
## Generate a new access token to join Kube Cluster
## That can be done with:
## kubeadm token generate
## If you leave that value empty, it will be created automaticly
# token: ""

## Generate a new certificatekey to deploy Kube Controlplane
## That can be done with:
## kubeadm alpha certs certificate-key
## If you leave that value empty, it will be created automaticly
certificate_key: ""
#######################################################################
#### automatic created values are stored in                        ####
#### roles/deploy-kubernetes/vars/main.yaml                        ####
#### and should be stored here after deployment for later usage    ####
#######################################################################

## if you want to delete the whole KubeCluster, set this value to true
## Handle with care, as all data will be lost
# reset_cluster: false

## Configure a Clustername
# clustername: kube

kubernetes:
  extendLVM: false
