---
- name: "{{item.name}} | load cinder keyring"
  shell: "kubectl get secret -n {{openstack.namespace}} cinder-volume-rbd-keyring -o json |jq -r '.data.key'|base64 -d"
  register: ceph_cinder_keyring
  when: openstack[item.name]['enabled'] and "{{item.name}}" == "nova"

- name: "{{item.name}} | generate config"
  template:
    src: "./templates/{{item.name}}.yaml.j2"
    dest: "/tmp/openstack_{{item.name}}.yaml"
  when: openstack[item.name]['enabled']

- name: "{{item.name}} | deploy helm chart"
  shell: helm upgrade --install {{item.name}} vanilla-openstack/{{ openstack[item.name]['chartName'] }} --version "{{ openstack[item.name]['chartVersion'] }}" --namespace "{{openstack.namespace}}" -f /tmp/openstack_{{item.name}}.yaml
  when: openstack[item.name]['enabled']
  retry: 3
  delay: 10

- name: "{{item.name}} | remove svc"
  k8s:
    namespace: "{{openstack.namespace}}"
    kind: Service
    name: "{{item.name}}"
    api_version: v1
    state: absent
  when: openstack[item.name]['enabled'] and openstack[item.name]['createService']

- name: "{{item.name}} | generate svc config"
  template:
    src: "./templates/svc.yaml.j2"
    dest: "/tmp/openstack_{{item.name}}-svc.yaml"
  when: openstack[item.name]['enabled'] and openstack[item.name]['createService']

- name: "{{item.name}} | deploy svc"
  k8s:
    src: "/tmp/openstack_{{item.name}}-svc.yaml"
    state: present
  when: openstack[item.name]['enabled'] and openstack[item.name]['createService']

- name: wait for pods to come up
  shell: kubectl get pods -o json -n "{{openstack.namespace}}" --field-selector=status.phase!=Succeeded
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
  retries: 120
  delay: 10
  when: item.wait

- name: "{{item.name}} | cleanup"
  file:
    path: "/tmp/openstack_{{item.name}}.yaml"
    state: absent
  when: openstack[item.name]['enabled']

- name: "{{item.name}} | cleanup"
  file:
    path: "/tmp/openstack_{{item.name}}-svc.yaml"
    state: absent
  when: openstack[item.name]['enabled'] and openstack[item.name]['createService']
