- name: Copy LetsEncrypt Issuer
  template:
    src: ./templates/letsencrypt.yaml.j2
    dest: /tmp/letsencrypt.yaml
  
- name: Create LetsEncrypt Issuer
  block:
    - name: Apply LetsEncrypt Issuer
      k8s:
        src: /tmp/letsencrypt.yaml
        state: present
      register: letsencryptIssuer
  rescue: 
    - name: restart cert-manager
      shell: "kubectl delete po -n {{certmanager.namespace}} -l app=cert-manager"
    - name: restart cert-manager webhook
      shell: "kubectl delete po -n {{certmanager.namespace}} -l app=webhook"
    - name: Wait for pods to be ready
      shell: kubectl wait -n {{certmanager.namespace}} --for=condition=Ready pods --timeout=60s --all 

- name: Retry LetsEncrypt Issuer
  k8s:
    src: /tmp/letsencrypt.yaml
    state: present
  when: letsencryptIssuer is not succeeded

- name: Cleanup LetsEncrypt Issuer
  file:
    path: /tmp/letsencrypt.yaml
    state: absent   
