---
- name: Test Playbook
  hosts: "{{host}}"
  gather_facts: false
  become: false
  tasks:
    - name: Creating Test File
      shell: touch /usr/workdir/testfile.txt

      #    - name: Debug Shell
      #debug:
      #  msg: "{{ hostvars[groups[host_group][0]]['key'] }}"
