---
- name: Test Playbook
  hosts: "{{host}}"
  gather_facts: false
  become: false
  tasks:
    - name: Counter
      shell: "echo {{ ansible_loop.index }}; sleep 5;"
      with_sequence: count='60'
      loop_control:
        extended: yes
