---
- name: create folder
  file: 
    path: "{{ ansible_env.HOME }}/{{ item }}/"
    state: directory
    mode: '750'
    owner: "{{ ansible_env.USER }}"
  loop:
    - "{{ kubernetes.clusterName }}"
    - .kube

- name: Copy admin.conf to Home directory
  become: true
  when: init_cluster is succeeded
  copy:
    src: "{{ kubeadmin_config }}"
    dest: ".kube/config"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0640
    remote_src: true

- name: install Cilium repository
  community.kubernetes.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io/

- name: Deploy latest version of Cilium
  community.kubernetes.helm:
    name: cilium
    chart_ref: cilium/cilium
    release_namespace: kube-system
    values: "{{ lookup('template', 'cilium-values.yaml.j2') | from_yaml }}"
    create_namespace: true
    chart_version: "1.8.3"
    wait: true

- name: Wait for control-plane pods become ready
  command: "kubectl wait --namespace=kube-system --for=condition=Ready pods --all --timeout=600s"

- name: restart kubedns
  command: kubectl delete po -n kube-system -l k8s-app=kube-dns
