---
- name: create join token
  command: kubeadm token create
  register: generated_token
  run_once: true

- name: save token
  lineinfile:
    path: /tmp/workerjoin_vars.yml
    regexp: '^(.*)token:(.*)$'
    line: "token: {{ generated_token.stdout }}"
    create: true

- name: fetch certificate key
  shell: "openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* //'"
  register: generated_certificate_key
  run_once: true

- name: save certificate key
  lineinfile:
    path: /tmp/workerjoin_vars.yml
    regexp: '^(.*)certificate_key(.*)$'
    line: "certificate_key: {{ generated_certificate_key.stdout }}"
    create: true

- name: Store vars localy
  fetch:
    src: /tmp/workerjoin_vars.yml
    dest: /tmp/
    flat: true
