rook:
  namespace: rook-ceph
  common:
    enabled: true
  operator:
    enabled: true
    csiEnableCephFS: true
    csiEnableRBD: true
    csiEnableGRPC: true
    image: rook/ceph:v1.4.1
  cluster:
    enabled: true
    image: ceph/ceph:v15.2.4
    name: rook-ceph
    dataHostDir: /var/lib/rook
    mon:
      count: 3
      allowMultiplePerNode: false
    dashboard:
      enabled: false
      ssl: true
    monitoring:
      enabled: false
    storage:
      useAllNodes: true
      useAllDevices: true
  storageclass:
    enabled: true
    name: rook-ceph-block
    failureDomain: host
    poolName: replicapool
    replicaLevel: 3
  toolbox:
    enabled: true
    name: rook-ceph-tools
    image: rook/ceph:v1.4.1
