---
- name: copy files to cluster folder
  copy:
    src:  "{{ item }}"   
    dest: "{{ ansible_env.HOME }}/{{ clustername }}/{{ item }}"
    owner: "{{ ansible_env.USER }}"
  loop: 
    - cf-operator.tgz
    - kubecf_release.tgz

- name: copy files to cluster folder
  template:
    src:  "{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ clustername }}/{{ item }}"
    owner: "{{ ansible_env.USER }}"
  loop:
    - cfoperator-values.yaml
    - kubecf-values.yaml

- name: create necessary namespaces
  k8s:
    name: "{{ item }}"
    api_version: v1
    kind: Namespace
    state: present
  loop:
  - "cf-operator"


- name: install CF Operator
  command: >
    helm install cf-operator \
    --namespace cf-operator \
    --set "global.singleNamespace.name=kubecf" \
    "{{ ansible_env.HOME }}/{{ clustername }}/cf-operator.tgz"

- pause:
    seconds: 20

- name: install Kubecf
  command: > 
    helm install kubecf \
    --namespace kubecf \
    --values "{{ ansible_env.HOME }}/{{ clustername }}/kubecf-values.yaml" \
    "{{ ansible_env.HOME }}/{{ clustername }}/kubecf_release.tgz"

