---
#- name: reconfigure repo.registry
#  set_fact:
#    vanillastackRegistry: "{{ repo.registry }}"
#  when: commercial_enabled != true
#
#- name: reconfigure repo.registry
#  set_fact:
#    vanillastackRegistry: "{{ commercial.registry.url }}"
#  when: commercial_enabled

- name: install VanillasStack Helm repository
  community.kubernetes.helm_repository:
    name: vanillastack
    repo_url: https://{{ repo.registry }}/chartrepo/vanillastack
  when: commercial_enabled != true
  ignore_errors: yes

- name: install VanillasStack Helm repository - commercial
  community.kubernetes.helm_repository:
    name: vanillastack
    repo_url: https://{{ commercial.registry.url }}/chartrepo/vanillastack
    repo_username: "robot${{commercial.registry.username}}"
    repo_password: "{{commercial.registry.key}}"
  when: commercial_enabled
  ignore_errors: yes

- name: update repo
  command: "helm repo update"
