---
- name: Prepare Bastion node
  hosts: master[0]
  become: true
  gather_facts: no
  roles:
    - role: prepare-node

- name: Install Keepalived
  hosts: haproxy
  become: true
  gather_facts: true
  roles:
    - role: install-haproxy
      action: 01_install_keepalived

- name: Install HaProxy
  hosts: haproxy
  become: true
  gather_facts: true
  roles:
    - role: install-haproxy
      action: 02_install_haproxy

- name: Configure Bastion Host
  hosts: kube_cluster
  become: true
  gather_facts: true
  roles:
    - role: deploy-kubernetes
      action: 01_configure_systems

- name: Configure Kube Systems
  hosts: master,worker
  become: true
  gather_facts: no
  roles:
    - role: deploy-kubernetes
      action: 02_configure_cluster

- name: generate secrets
  hosts: localhost
  connection: local
  gather_facts: yes
  roles:
    - role: deploy-kubernetes
      action: 02-1-generate-certificate

- name: Init KubeCluster
  hosts: master[0]
  become: true
  gather_facts: no
  roles:
    - role: deploy-kubernetes
      action: 03_deploy_kubernetes

- name: Add Master to KubeCluster
  hosts: master[1:]
  become: true
  gather_facts: no
  roles:
    - role: deploy-kubernetes
      action: 04_add_nodes

- name: Add worker to KubeCluster
  hosts: worker
  become: true
  gather_facts: no
  roles:
    - role: deploy-kubernetes
      action: 05_add_worker

- name: Deploy Networking
  hosts: master[0]
  gather_facts: yes
  roles:
    - role: deploy-kubernetes
      action: 06_configure_network

- name: Deploy Nginx-Ingress
  hosts: master[0]
  become: false
  gather_facts: false
  roles:
    - role: helm-nginx-ingress

- name: Deploy Rook
  hosts: master[0]
  become: false
  gather_facts: false
  roles:
    - role: deploy-rook

- name: Deploy Cert Manager
  hosts: master[0]
  become: false
  gather_facts: true
  roles:
    - role: helm-cert-manager

- name: Deploy OpenStack
  hosts: master[0]
  become: false
  gather_facts: no
  roles:
    - role: deploy-openstack
