---
- name: Install Keepalived
  hosts: haproxy
  become: true
  gather_facts: true
  roles:
    - role: install-haproxy
      action: 01_install_keepalived
- name: Install HaProxy
  hosts: haproxy
  become: true
  gather_facts: true
  roles:
    - role: install-haproxy
      action: 02_install_haproxy






