---
#- name: Reset Nodes
#  hosts: master,worker
#  become: true
#  gather_facts: false
#  roles:
#    - role: reset-kubernetes

- name: Configure Hosts
  hosts: kube_cluster
  become: true
  gather_facts: true
  roles:
    - role: deploy-kubernetes
      action: 01_configure_systems
      when: ansible_distribution != 'Debian'
    - role: deploy-kubernetes
      action: 01_configure_systems_debian
      when: ansible_distribution == 'Debian'

- name: Configure Kube Systems
  hosts: master,worker
  become: true
  gather_facts: no
  roles:
    - role: deploy-kubernetes
      action: 02_configure_cluster

- name: generate secrets
  hosts: bastion
  gather_facts: yes
  roles:
    - role: deploy-kubernetes
      action: 02-1-generate-certificate

- name: Init KubeCluster
  hosts: master[0]
  become: true
  gather_facts: no
  roles:
    - role: deploy-kubernetes
      action: 03_deploy_kubernetes

- name: Add Master to KubeCluster
  hosts: master[1:]
  become: true
  gather_facts: no
  roles:
    - role: deploy-kubernetes
      action: 04_add_nodes

- name: Add worker to KubeCluster
  hosts: worker
  become: true
  gather_facts: no
  roles:
    - role: deploy-kubernetes
      action: 05_add_worker

- name: Deploy Networking
  hosts: master[0]
  gather_facts: yes
  roles:
    - role: deploy-kubernetes
      action: 06_configure_network

- name: Label Nodes
  hosts: master[0]
  gather_facts: yes
  roles:
    - role: deploy-kubernetes
      action: 07-label_nodes
