---
# defaults file for install-guacamole
guacamole:
  imageTag: latest
  enabled: false
  namespace: guacamole
  postgres:
    maxConnections: 400
    backup:
      enabled: false
      cronjob: "30 */2 * * *"
    version: "12"
    replicas: "2"
    size: "20Gi"
<<<<<<< HEAD
=======

>>>>>>> b203a886eee8acb1773ce7e559a5527d80c9e8ef
